openapi: 3.0.0
info:
  version: 0.0.1
  title: message API
servers:
  - url: 'http://localhost:3000'
paths:
  /messages:
    post:
      summary: 'Sample endpoint: Send a message and see the response'
      tags:
        - messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
                  example: this is a chat message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  status:
                    type: number
        '400': # status code
          description: Bad Request
        '404': # status code
          description: Cannot find any appropriate response
